name: 'RainArchiver'
description: 'Rain Radar Fetcher for archiving rain area map'
branding:
  icon: archive
  color: yellow
inputs:
  outputDirectory:
    description: >
      Static feeds output directory
    default: 'contents'
  branch:
    description: >
      Output branch
    default: 'contents'
  token:
    description: >
      Github token for pulling repository information
    default: ${{ github.token }}
  customDomain:
    description: >
      Enable custom domain name for the site generator
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
