name: Fetcher

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 * * * *'

jobs:
  singapore:
    runs-on: ubuntu-latest
    name: Singapore
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Setup yarn, npm
        run: |
          yarn install
      - name: Fetch singapore
        run: |
          node index.js -r singapore
      - name: Fetch malaysia
        run: |
          node index.js -r malaysia
